version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build: 
    docker: 
      - image: circleci/node:12.18


    # Service container image available at `host: localhost`
    
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: example
          POSTGRES_PASSWORD: example
          POSTGRES_DB: test
        
    steps:
      - checkout


      # Bundle install dependencies
     
      - run: sudo apt install -y postgresql-client || true

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: cd api && npm ci


      - setup_remote_docker
      
      - run: |
          cd api
          TAG="0.1.${CIRCLE_BUILD_NUM}"
          LATEST="latest"
          docker build -t crshlab/cicd_starter:$TAG .
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          docker push crshlab/cicd_starter:$TAG
          docker tag crshlab/cicd_starter:$TAG crshlab/cicd_starter:$LATEST
          docker push crshlab/cicd_starter:$LATEST
